# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
version = np.__version__
version

'2.2.5'

In [5]:
config = np.show_config()
config

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-m0ne3oqc/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-m0ne3oqc/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-m0ne3oqc/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-m0ne3oqc/cp312-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  US

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
array = np.zeros(10)
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
array = np.zeros((3, 4))
print(array)
print("Array Data Type: ", array.dtype)
print("Array Shape: ", array.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array Data Type:  float64
Array Shape:  (3, 4)


#### 4. How to find the memory size of any array (★☆☆)

In [17]:
# For Numpy

np_array = np.array([1,2,3,4,5])
print("Item Size: ",np_array.itemsize)
print("Array Size: ",np_array.size)

size = np_array.itemsize * np_array.size
print("Size of Numpy array :", size)

Item Size:  8
Array Size:  5
Size of Numpy array : 40


In [16]:
# For normal arrays

import sys
py_array = [1,2,3,4,5]
print("Array size: ", py_array.__sizeof__())
size = sys.getsizeof(1) * len(py_array)
print("Size and length of Python array :", size)

Array size:  88
Size and length of Python array : 140


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [18]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
result = []
for num in range(10, 49):
    result.append(num)
print(result)

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [31]:
vector = np.array([1, 2, 3, 4, 5])
print(vector[::-1])

[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [35]:
array = np.arange(9)
print(array)
array = array.reshape(3,3)
array

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
array = np.random.randint(0,10, size=(3,3))
print(array)

[[6 9 7]
 [4 8 7]
 [8 8 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [45]:
array = np.array([1, 2, 0, 0, 4, 0])
array = array[array != 0]
print("Non Zero Elemnts indices are: ", array.nonzero())
print("Non Zero Values are:c",array)

Non Zero Elemnts indices are:  (array([0, 1, 2]),)
Non Zero Values are:c [1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [37]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [46]:
array = np.identity(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [43]:
array = np.arange(27).reshape(3, 3, 3)
array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [52]:
array = np.random.randint(0,500, size=(10,10))
print("Max number is: ",array.max())
print("Min number is: ",array.min())
print("Sum of array number is: ",array.sum())
print("Mean is: ",array.mean())
print(array.sum(axis=0))
print(array.sum(axis=1))


Max number is:  492
Min number is:  18
Sum of array number is:  25373
Mean is:  253.73
[2360 2325 2129 2205 3040 2702 2908 2821 2436 2447]
[2619 2119 2281 2824 3130 2853 1955 1836 3109 2647]


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [51]:
array = np.random.randint(0, 10, size=(30))
print(array)
print("Mean is: ",array.mean())

[1 4 2 8 5 9 7 4 2 9 3 1 6 2 1 7 2 0 4 3 7 4 0 9 5 7 3 2 8 8]
Mean is:  4.433333333333334


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [60]:
array = np.zeros((4, 4))
array[0] = 1
array[3] = 1
array[1][0] = 1
array[1][3] = 1
array[2][0] = 1
array[2][3] = 1

array

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [65]:
array = np.zeros((4, 4))
array[0,:] = 1
array[-1,:] = 1
array[:,0] = 1
array[:,-1] = 1
array

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [76]:
array = np.random.randint(0, 30, size=(4, 4))
print(array)
array[0,:] = 0
array[-1,:] = 0
array[:,0] = 0
array[:,-1] = 0
print(array)

[[24  7 25 16]
 [23  2 11 18]
 [13 17 13  0]
 [13  8 23 28]]
[[ 0  0  0  0]
 [ 0  2 11  0]
 [ 0 17 13  0]
 [ 0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [77]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [83]:
array = np.diag([1, 2, 3, 4], k=0)
print(array)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [86]:
checkerboard = np.zeros((8,8), dtype=int)

# Fill with a checkerboard pattern
checkerboard[1::2, ::2] = 1  # Set 1s in alternating rows & columns
checkerboard[::2, 1::2] = 1  # Shift the pattern in even rows

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Normalize a 5x5 random matrix (★☆☆)

In [87]:
matrix = np.random.rand(5,5)

# Min-Max Normalization
min_val = matrix.min()
max_val = matrix.max()
normalized_matrix = (matrix - min_val) / (max_val - min_val)

print("Original Matrix:\n", matrix)
print("\nMin-Max Normalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[0.24741289 0.79617704 0.9244755  0.25203563 0.24378219]
 [0.71459418 0.69298222 0.96413228 0.16348814 0.31149886]
 [0.74337445 0.09168358 0.91053441 0.59167006 0.4276311 ]
 [0.53317473 0.47533834 0.83562464 0.01089836 0.45624207]
 [0.16625289 0.55198922 0.12283284 0.64306137 0.15154723]]

Min-Max Normalized Matrix:
 [[0.24811804 0.82380481 0.95839765 0.25296757 0.24430921]
 [0.73821946 0.7155472  1.         0.1600759  0.31534809]
 [0.7684117  0.08474858 0.9437726  0.60926462 0.43717784]
 [0.54789948 0.48722562 0.86518772 0.         0.46719247]
 [0.16297629 0.56763702 0.11742603 0.66317721 0.14754917]]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [88]:
A = np.random.randint(1, 30, (5, 3))
B = np.random.randint(1, 50, (3, 2))

# Matrix multiplication using np.dot()
C = np.dot(A, B)

print("Matrix A (5x3):\n", A)
print("\nMatrix B (3x2):\n", B)
print("\nResultant Matrix C (5x2):\n", C)

Matrix A (5x3):
 [[ 5  3 13]
 [20  8  7]
 [13 23 11]
 [16 25 16]
 [12  6 14]]

Matrix B (3x2):
 [[11 19]
 [30 42]
 [ 2 11]]

Resultant Matrix C (5x2):
 [[ 171  364]
 [ 474  793]
 [ 855 1334]
 [ 958 1530]
 [ 340  634]]


#### 22. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [79]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 23. How to find common values between two arrays? (★☆☆)

In [89]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

array = np.intersect1d(array1, array2)
print("Intersection of two arrays: ", array)

Intersection of two arrays:  [4 5]
