### Questions 1

Create a matrix of 5x5 with random integers, after that swap its first and last rows.

In [6]:
import numpy as np

matrix = np.random.randint(1, 101, size=(5, 5))
print(matrix)
print("==============================")
# matrix[[0, -1]] = matrix[[-1, 0]]
matrix[0] = matrix[-1]
matrix[-1] = matrix[0]
print(matrix)

[[28 41 15  3 96]
 [62  8 62 72 81]
 [55 61 66 23 26]
 [24 24 80 37 93]
 [42 61 24 24 50]]
[[42 61 24 24 50]
 [62  8 62 72 81]
 [55 61 66 23 26]
 [24 24 80 37 93]
 [42 61 24 24 50]]


### Question 2

Create a 2D array, remove all rows that contain at least one zero.

In [21]:
array = np.array([
    [1, 2, 3],
    [4, 0, 6],
    [7, 8, 9]
])
print(array)

filtered_arr = array[~np.any(array == 0, axis=1)]
print(filtered_arr)

[[1 2 3]
 [4 0 6]
 [7 8 9]]
[[1 2 3]
 [7 8 9]]


### Question 3

Write a NumPy program to find the real and imaginary parts of an array of complex numbers.<br>
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

In [23]:
complex_array = np.array([1.00000000+0.j, 0.70710678+0.70710678j])

# Extract real and imaginary parts
real_part = complex_array.real
imaginary_part = complex_array.imag

print("Original array:", complex_array)
print("Real parts:", real_part)
print("Imaginary parts:", imaginary_part)

Original array: [1.        +0.j         0.70710678+0.70710678j]
Real parts: [1.         0.70710678]
Imaginary parts: [0.         0.70710678]


### Question 4

Write a NumPy program to remove the duplicate elements of an array.<br>
Original array:
[10 10 20 20 30 30]


In [6]:
arr = np.array([10,10, 20, 20, 30, 30])
removed = np.unique(arr)
removed

array([10, 20, 30])

### Question 5

Write a NumPy program to create a 3x3x3 array with random values.

In [3]:
array = np.arange((27))
print(array)
new_array = array.reshape(3,3,3)
print(new_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


### Question 6

Write a NumPy program to create a random vector of size 10 and sort it.<br>
<b>Note:</b> Do not use builtin sorting function

In [20]:
vector = np.random.randint(1, 100, size=10)
print(vector)

sorted_vect = np.sort(vector)
sorted_vect

[61  1 90 10 16 88 50 66 87 97]


array([ 1, 10, 16, 50, 61, 66, 87, 88, 90, 97], dtype=int32)

### Question 7

Write a NumPy program to check two random arrays are equal or not.

In [22]:
arr1 = np.random.randint(0, 10, size=(2, 2))
arr2 = np.random.randint(0, 10, size=(3, 3))

checked = np.array_equal(arr1,arr2)
checked

False

### Question 8 

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.<br>

Original array:<br>
[[10 40]<br>
[30 20]]

In [24]:
arr = np.array([[10, 40], [30, 20]])

# Sort along the first axis (rows)
sorted_first_axis = np.sort(arr, axis=0)

# Sort along the last axis (columns)
sorted_last_axis = np.sort(arr, axis=1)

# Sort the flattened array
sorted_flattened = np.sort(arr.flatten())

print("Original array:\n", arr)
print("\nSorted along the first axis (rows):\n", sorted_first_axis)
print("\nSorted along the last axis (columns):\n", sorted_last_axis)
print("\nSorted flattened array:\n", sorted_flattened)

Original array:
 [[10 40]
 [30 20]]

Sorted along the first axis (rows):
 [[10 20]
 [30 40]]

Sorted along the last axis (columns):
 [[10 40]
 [20 30]]

Sorted flattened array:
 [10 20 30 40]


### Question 9

Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.<br>

Original array:<br>
[-1.6 -1.5 -0.3 0.1 1.4 1.8 2. ]

In [25]:
arr = np.array([-1.6, -1.5, -0.3, 0.1, 1.4, 1.8, 2.0])

floor_values = np.floor(arr)
ceiling_values = np.ceil(arr)
truncated_values = np.trunc(arr)

print("Original array:\n", arr)
print("\nFloor values:\n", floor_values)
print("\nCeiling values:\n", ceiling_values)
print("\nTruncated values:\n", truncated_values)

Original array:
 [-1.6 -1.5 -0.3  0.1  1.4  1.8  2. ]

Floor values:
 [-2. -2. -1.  0.  1.  1.  2.]

Ceiling values:
 [-1. -1. -0.  1.  2.  2.  2.]

Truncated values:
 [-1. -1. -0.  0.  1.  1.  2.]


### Questions 10

Write a NumPy program to display all the dates for the month of March, 2017

In [24]:
dates = np.arange('2017-03-01', '2017-04-01', dtype='datetime64[D]')
dates

array(['2017-03-01', '2017-03-02', '2017-03-03', '2017-03-04',
       '2017-03-05', '2017-03-06', '2017-03-07', '2017-03-08',
       '2017-03-09', '2017-03-10', '2017-03-11', '2017-03-12',
       '2017-03-13', '2017-03-14', '2017-03-15', '2017-03-16',
       '2017-03-17', '2017-03-18', '2017-03-19', '2017-03-20',
       '2017-03-21', '2017-03-22', '2017-03-23', '2017-03-24',
       '2017-03-25', '2017-03-26', '2017-03-27', '2017-03-28',
       '2017-03-29', '2017-03-30', '2017-03-31'], dtype='datetime64[D]')

### Question 11

Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.

In [27]:
import datetime

start_time = np.datetime64('2025-04-22T00:00')
hours = np.arange(24)
datetime_array = start_time + np.array(hours, dtype='timedelta64[h]')
python_datetime_array = datetime_array.astype(datetime.datetime)
print(python_datetime_array)

[datetime.datetime(2025, 4, 22, 0, 0) datetime.datetime(2025, 4, 22, 1, 0)
 datetime.datetime(2025, 4, 22, 2, 0) datetime.datetime(2025, 4, 22, 3, 0)
 datetime.datetime(2025, 4, 22, 4, 0) datetime.datetime(2025, 4, 22, 5, 0)
 datetime.datetime(2025, 4, 22, 6, 0) datetime.datetime(2025, 4, 22, 7, 0)
 datetime.datetime(2025, 4, 22, 8, 0) datetime.datetime(2025, 4, 22, 9, 0)
 datetime.datetime(2025, 4, 22, 10, 0)
 datetime.datetime(2025, 4, 22, 11, 0)
 datetime.datetime(2025, 4, 22, 12, 0)
 datetime.datetime(2025, 4, 22, 13, 0)
 datetime.datetime(2025, 4, 22, 14, 0)
 datetime.datetime(2025, 4, 22, 15, 0)
 datetime.datetime(2025, 4, 22, 16, 0)
 datetime.datetime(2025, 4, 22, 17, 0)
 datetime.datetime(2025, 4, 22, 18, 0)
 datetime.datetime(2025, 4, 22, 19, 0)
 datetime.datetime(2025, 4, 22, 20, 0)
 datetime.datetime(2025, 4, 22, 21, 0)
 datetime.datetime(2025, 4, 22, 22, 0)
 datetime.datetime(2025, 4, 22, 23, 0)]


### Question 12

Write a NumPy program to concatenate element-wise two arrays of string.<br>
<b>Example </b>
Array1:<br>
['Python' 'PHP']<br>
Array2:<br>
[' Java' ' C++']<br>
new array:<br>
['Python Java' 'PHP C++']<br>

In [33]:
arr1 = np.array(['Python' ,'PHP'])
arr2 = np.array(['Java' 'C++'])
new = np.char.add(arr1,arr2)
print(new, end=' ')

['PythonJavaC++' 'PHPJavaC++'] 